### ISSUE TITLE
Setting replicas to 0 has same effect than setting replicas to 1

### ISSUE THREAD

**Issue by bpolaszek** [Baldinof/caddy-supervisor#4]
Hello there,

I tried to temporarily disable a command by setting its `replicas` to `0` but it didn't work - it looked like `replicas` directive is then simply ignored and 1 replica is spawned. 

It would be great tho, it would avoid commenting lines one by one (in vim, ofc!) and disabling replicas this way would (presumably) be possible by using an env var, making it possible to have same Caddyfile on different machines, but a different number of workers (or no worker at all) when relevant.

Thanks!
Ben

**Comment by Baldinof** [comment]
Hi, thank you for opening this!

I will try to have a look this weekend :)

Also, sorry for the late response.

**Comment by Baldinof** [comment]
Can you give #6 a try before I merge?

**Comment by bpolaszek** [comment]
Works like a charm! 👌 🙏
